package com.facugl.banking_system_server.users.util;

public enum RolePermissionEnum {
    CREATE_ONE_ACCOUNT,
    GET_ONE_ACCOUNT,
    GET_ALL_ACCOUNTS,
    GET_OWN_ACCOUNTS,
    UPDATE_ONE_ACCOUNT,
    UPDATE_ACCOUNT_STATUS,
    DELETE_ONE_ACCOUNT,
    DEPOSIT_INTO_ACCOUNT,
    WITHDRAW_FROM_ACCOUNT,
    TRANSFER_BETWEEN_ACCOUNTS,
    CHECK_ACCOUNT_BALANCE,
    GET_ALL_TRANSACTIONS,
    GET_OWN_TRANSACTIONS,
    READ_MY_PROFILE
}
