spring:
  profiles:
    active: dev

  application:
    name: banking-system-server

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true

security:
  default:
    role: "CUSTOMER"
  jwt:
    expiration-in-minutes: ${JWT_EXPIRATION_MINUTES:30}
